### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by HenryNguyen5** [haadcode/orbit-db#140]
I did the following steps:

git clone https://github.com/haadcode/orbit-db.git
cd orbit-db
npm install
npm run build
npm test

Which spits out the following errors:

  Orbit Client with js-ipfs-api
    1) "before all" hook
(node:23742) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'stopDaemon' of undefined
(node:23742) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    2) "after all" hook

  106 passing (22s)
  2 failing

  1) Orbit Client with js-ipfs-api "before all" hook:
     Error: ENOENT: no such file or directory, open '/tmp/orbit-db-tests/config'
      at Object.fs.openSync (fs.js:557:18)
      at Object.fs.readFileSync (fs.js:467:33)
      at parseConfig (node_modules/ipfsd-ctl/src/node.js:47:21)
      at Node.startDaemon (node_modules/ipfsd-ctl/src/node.js:127:5)
      at ipfsDaemon.init (node_modules/ipfs-daemon/ipfs-daemon.js:89:22)
      at configureNode (node_modules/ipfsd-ctl/src/node.js:99:11)
      at end (node_modules/run-series/index.js:8:15)
      at done (node_modules/run-series/index.js:11:10)
      at Stream.each (node_modules/run-series/index.js:16:43)
      at Socket.handleEnd (node_modules/duplexer/index.js:81:21)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)

  2) Orbit Client with js-ipfs-api "after all" hook:
     Error: timeout of 20000ms exceeded. Ensure the done() callback is being called in this test.

npm ERR! Test failed.  See above for more details.

Currently trying to run this from Bash for Windows 10

**Comment by haadcode** [comment]
Hi @HenryNguyen5, thanks for reporting this issue! We're currently having some problems with Windows, see https://github.com/haadcode/orbit-db/issues/125. Hopefully we'll get this fixed soon.

**Comment by HenryNguyen5** [comment]
Hi @haadcode, I'm not sure if its an issue with Windows in particular since Bash for Windows is actually a full Linux subsystem. Its running Ubuntu 16.04.

**Comment by haadcode** [comment]
This should be now fixed in 0.16.0. Let us know if you still experience problems.
